node {
    docker.image('node:18-bullseye').inside('-p 3000:3000') {
        environment {
            CI = 'true'
        }

        stage('Build') {
            try {
                sh 'npm install'
            } catch (err) {
                error("Build failed: ${err}")
            }
        }

        stage('Test') {
            try {
                sh './jenkins/scripts/test.sh'
            } catch (err) {
                error("Test failed: ${err}")
            }
        }

        stage('Manual Approval') {
            input message: 'Lanjutkan ke tahap Deploy? (Klik "Proceed" untuk melanjutkan)'
        }

        stage('Deploy') {
            def ec2Ip = '18.218.217.151'
            def ec2User = 'admin'

            withCredentials([file(credentialsId: 'my-ec2-key', variable: 'EC2_KEY')]) {
                try {
                    sh '''
                    chmod 600 $EC2_KEY
                    scp -o StrictHostKeyChecking=no -i $EC2_KEY -r ./build $ec2User@$ec2Ip:/home/admin/my-node-app
                    '''

                    sh '''
                    ssh -o StrictHostKeyChecking=no -i $EC2_KEY $ec2User@$ec2Ip "
                    cd /home/admin/my-node-app && 
                    nohup npm start > app.log 2>&1 &
                    "
                    '''
                    echo "Aplikasi berhasil dideploy dan berjalan di EC2"
                } catch (err) {
                    error("Delivery process failed: ${err}")
                }
            }

            sleep 60
            echo "Tahap deploy selesai."
        }
    }
}
