node {
    def buildDir = "${env.WORKSPACE}/build"

    docker.image('node:16-bullseye').inside("-v ${buildDir}:/app -p 3000:3000") {
        environment {
            CI = 'true'
        }

        stage('Build') {
            try {
                sh 'npm install'
                sh 'npm run build'
                // sh 'cp -r ./build/* /app/'
            } catch (err) {
                error("Build failed: ${err}")
            }
        }

        stage('Test') {
            try {
                sh './jenkins/scripts/test.sh'
            } catch (err) {
                error("Test failed: ${err}")
            }
        }

        stage('Manual Approval') {
            input message: 'Lanjutkan ke tahap Deploy? (Klik "Proceed" untuk melanjutkan)'
        }
    }

    stage('Deploy') {
        def ec2Ip = '18.218.217.151'
        def ec2User = 'admin'

        withCredentials([file(credentialsId: 'my-ec2-key', variable: 'EC2_KEY')]) {
            try {
                // Konfigurasi NGINX di EC2
                sh """
                    ssh -o StrictHostKeyChecking=no -i $EC2_KEY ${ec2User}@${ec2Ip} "
                    sudo rm -rf /home/admin/react-app
                    sudo systemctl restart nginx
                    "
                """

                // Salin hasil build ke EC2
                sh """
                    chmod 600 $EC2_KEY
                    scp -o StrictHostKeyChecking=no -i $EC2_KEY -r ${buildDir}/* ${ec2User}@${ec2Ip}:/home/admin/react-app
                """

                
                echo "Aplikasi berhasil dideploy dan disajikan menggunakan NGINX silahkan akses di http://$ec2Ip"
            } catch (err) {
                error("Delivery process failed: ${err}")
            }
        }

        sleep 60
        echo "Tahap deploy selesai."
    }
}