node {
    def buildDir = "${env.WORKSPACE}/build"

    docker.image('node:16-bullseye').inside("-v ${buildDir}:/app -p 3000:3000") {
        environment {
            CI = 'true'
        }

        stage('Build') {
            try {
                sh 'npm install'
                sh 'npm run build'
                // Copy hasil build ke volume yang terhubung ke host
                // sh 'cp -r ./build /app/'
                sh 'cp package.json ./build/'
                sh 'ls ./build'
            } catch (err) {
                error("Build failed: ${err}")
            }
        }

        stage('Test') {
            try {
                sh './jenkins/scripts/test.sh'
            } catch (err) {
                error("Test failed: ${err}")
            }
        }

        stage('Manual Approval') {
            input message: 'Lanjutkan ke tahap Deploy? (Klik "Proceed" untuk melanjutkan)'
        }
    }

    stage('Deploy') {
        def ec2Ip = '18.218.217.151'
        def ec2User = 'admin'

        withCredentials([file(credentialsId: 'my-ec2-key', variable: 'EC2_KEY')]) {
            try {
                // Pastikan build hasil dari kontainer tersedia
                sh """
                    chmod 600 $EC2_KEY
                    scp -o StrictHostKeyChecking=no -i $EC2_KEY -r ${buildDir} ${ec2User}@${ec2Ip}:/home/admin/react-app
                """

                sh """
                    ssh -o StrictHostKeyChecking=no -i $EC2_KEY ${ec2User}@${ec2Ip} "
                    cd /home/admin/react-app &&
                    npm install &&
                    npm run build &&
                    nohup npm start > app.log 2>&1 &
                    "
                """
                echo "Aplikasi berhasil dideploy dan berjalan di EC2"
            } catch (err) {
                error("Delivery process failed: ${err}")
            }
        }

        sleep 60
        echo "Tahap deploy selesai."
    }
}
